version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 764057086582.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=764057086582.dkr.ecr.ap-south-1.amazonaws.com/gaia-db
  build:
    commands:
      - echo Build started on date
      - echo Building the Docker image...
      - docker build -t  mongodb:v1 -f Dockerfile-db .
      - docker tag mongodb:v1 764057086582.dkr.ecr.ap-south-1.amazonaws.com/gaia-db:latest
  post_build:
    commands:
      - echo Build completed on date
      - echo Pushing the Docker image...
      - docker push 764057086582.dkr.ecr.ap-south-1.amazonaws.com/gaia-db:latest
